// packages/vue-apge/src/components/SearchInput.vue
<template>
  <div class="block block_input">
    <input v-model="filters.name" id="searchInput" />
    <label for="searchInput">Search by keyword:</label>
  </div>
</template>

<script>
export default {
  name: "SearchInput",
};
</script>
<script setup>
import { toRefs } from "vue";

const props = defineProps({
  filters: Object,
});
const { filters } = toRefs(props);
</script>

// packages/react-apge/src/components/SearchInput/SearchInput.jsx
import React, { useId } from "react";

const SearchInput = ({ filters, setFilter }) => {
  const inpId = useId();

  const handleChange = (e) => {
    let { name, value } = e.target;
    setFilter(name, value);
  };

  return (
    <div className="block block_input">
      <input
        value={filters.name}
        onChange={handleChange}
        name="name"
        id={inpId}
      />
      <label htmlFor={inpId}>Search by keyword:</label>
    </div>
  );
};

export default SearchInput;
