// packages/vue-apge/src/components/RadioButton.vue
<template>
  <div className="radio">
    <input
      :onClick="onChange"
      :value="label"
      :name="name"
      type="radio"
      :checked="checked"
      :id="id"
    />
    <label :for="id">{{ label }}</label>
  </div>
</template>

<script>
export default {
  name: "RadioButton",
  props: {
    label: String,
    checked: Boolean,
    onChange: Function,
    name: String,
  },
  mounted() {
    this.id = this._uid;
  },
};
</script>

// packages/react-apge/src/components/RadioButton/RadioButton.jsx
import React, { useId } from "react";

const RadioButton = ({checked, onChange, name, label }) => {
  const inpId = useId();
  return (
    <div className="radio">
      <input
        onClick={onChange}
        value={label}
        name={name}
        type="radio"
        checked={checked}
        id={inpId}
      />
      <label htmlFor={inpId}>{label}
       </label>
      
    </div>
  );
};

export default RadioButton;
