// packages/react-apge/src/components/Good/GoodComponent.jsx
import React from "react";
import Tag from "../Tag";
 
const GoodComponent = ({ data: { name, price, type, color, size, image } }) => {
  return (
    <div className="good_item">
      <div className="good_item_pic">
        <img src={image} alt={name} />
      </div>
      <div className="good_item_body">
        <h3 className="good_item_title">{name}</h3>
        <p className="good_item_desc">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore
          corrupti, debitis omnis error sunt nesciunt sequi odio iusto nostrum.
        </p>
        <b className="good_item_price">{price}.$</b>
        <div className="good_item_tags">
          <Tag title={type} />
          <Tag title={color} />
          <Tag title={size} />
        </div>
      </div>
    </div>
  );
};

export default GoodComponent;

// packages/vue-apge/src/components/Good.vue
<template>
  <div class="good_item">
    <div class="good_item_pic">
      <img :src="good.image" :alt="good.image" />  
    </div>
    <div class="good_item_body">
      <h3 class="good_item_title">{{good.name}}</h3>
      <p class="good_item_desc">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore
        corrupti, debitis omnis error sunt nesciunt sequi odio iusto nostrum.
      </p>
      <b class="good_item_price">{{good.price}}.$</b>
      <div class="good_item_tags">
       <!--  <Tag title="{type}" />
        <Tag title="{color}" />
        <Tag title="{size}" />  
        -->
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "GoodComponent",
  props: {
    good: {
      default: null,
      type: Object
    },
  },
};
</script>
